# Linear Algebra

In [2]:
import numpy as np
import matplotlib.pyplot as plt

## Vectors

### By [vectors 1.0.0](https://pypi.python.org/pypi/vectors)

In [3]:
from vectors import Point, Vector

#### Vectors

In [4]:
v1 = Vector(1,2,3)
v1

Vector(1, 2, 3)

In [5]:
v2 = Vector(3,5,6)
v2

Vector(3, 5, 6)

#### Vector Operation

In [6]:
# Add a scalar value
v1.add(2)

Vector(3.0, 4.0, 5.0)

In [7]:
# Add a vector
v1.sum(v2)

Vector(4.0, 7.0, 9.0)

In [8]:
# Scalar multiplication
v1.multiply(4)

Vector(4.0, 8.0, 12.0)

In [9]:
# Inner/Dot product
v1.dot(v2)

31

#### Note:
- Only for 3-dimension vectors (but it's easy to make it n-dimension)
- Implementations are not beautiful enough. Modify build-in methods can make it better. For instance,


In [29]:
# A demo
# Reference: https://www.oschina.net/question/253614_115412
class MyVector(Vector):        
    def __add__(self, obj):
        if isinstance(obj, int):
            return self.add(obj)
        elif isinstance(obj, Vector):
            return self.sum(obj)
        else:
            raise TypeError, "unsupported operand type(s) for +: '%s' and '%s'"%(type(self),type(obj)) 
    
    def __mul__(self, obj):
        if isinstance(obj, int):
            return self.multiply(obj)
        elif isinstance(obj, Vector):
            return self.dot(obj)
        else:
            raise TypeError, "unsupported operand type(s) for *: '%s' and '%s'"%(type(self),type(obj))

In [12]:
v1 = MyVector(1,2,3)
v1

MyVector(1, 2, 3)

In [13]:
v2 = MyVector(3,5,6)
v2

MyVector(3, 5, 6)

In [18]:
v1+2

MyVector(3.0, 4.0, 5.0)

In [19]:
v1+v2

MyVector(4.0, 7.0, 9.0)

In [22]:
v1+'vector'

TypeError: unsupported operand type(s) for +: '<class '__main__.MyVector'>' and '<type 'str'>'

In [20]:
v1*3

MyVector(3.0, 6.0, 9.0)

In [21]:
v1*v2

31

In [23]:
v1*"vector"

TypeError: unsupported operand type(s) for *: '<class '__main__.MyVector'>' and '<type 'str'>'

### By [numpy.linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

In [15]:
v1 = np.array([1,2,3])
v2 = np.array([3,5,6])

In [16]:
np.dot(v1,v2)

56

Note: The implement of Vector and its methods can be developed in NumPy. In addition, some methods to plot vectors can be packaged. 

## Matrix

## By [np.matrix](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html)

### Matrix

In [31]:
m1 = np.matrix([[1,2,3],[2,4,5],[3,4,5]])
m1

matrix([[1, 2, 3],
        [2, 4, 5],
        [3, 4, 5]])

In [32]:
m2 = np.matrix([[3,6,2],[4,6,7],[9,7,1]])
m2

matrix([[3, 6, 2],
        [4, 6, 7],
        [9, 7, 1]])

### Number of Rows and Columns 

In [36]:
m1.shape

(3, 3)

### Transpose

In [38]:
m1.T

matrix([[1, 2, 3],
        [2, 4, 4],
        [3, 5, 5]])

### Add

In [22]:
m1+m2

matrix([[ 4,  8,  5],
        [ 6, 10, 12],
        [12, 11,  6]])

### Scalar Multiply

In [33]:
m1*5

matrix([[ 5, 10, 15],
        [10, 20, 25],
        [15, 20, 25]])

### Matrix Multiply

In [34]:
# matrix operation
m1*m2

matrix([[38, 39, 19],
        [67, 71, 37],
        [70, 77, 39]])

In [35]:
# matrix operation
m2*m1

matrix([[21, 38, 49],
        [37, 60, 77],
        [26, 50, 67]])

### Determinant

In [40]:
np.linalg.det(m1)

-2.0000000000000004

### Solve Equations

In [46]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [47]:
y = np.ones((2,1))
y

array([[ 1.],
       [ 1.]])

In [52]:
x = np.dot(np.linalg.inv(a), y)
x

array([[-1.],
       [ 1.]])

## Exercise

In [ ]:
class Optimization(object):
    def __init__(self):
        pass

